# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from spot_cam/PTZStateArray.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import spot_cam.msg
import std_msgs.msg

class PTZStateArray(genpy.Message):
  _md5sum = "c71a65fc59258e7303baf75176b74b2b"
  _type = "spot_cam/PTZStateArray"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """spot_cam/PTZState[] ptzs
================================================================================
MSG: spot_cam/PTZState
# This message covers two different types which have the exact same field names, to reduce duplication. Depending on the topic,
# The meaning of the pan/tilt/zoom values changes.
# https://dev.bostondynamics.com/protos/bosdyn/api/proto_reference#ptzposition
# https://dev.bostondynamics.com/protos/bosdyn/api/proto_reference#ptzvelocity
std_msgs/Header header
# Description of the ptz
spot_cam/PTZDescription ptz
# degrees or degrees per second
float32 pan
# degrees or degrees per second
float32 tilt
# zoom level or zoom level per second
float32 zoom
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: spot_cam/PTZDescription
# https://dev.bostondynamics.com/protos/bosdyn/api/proto_reference#ptzdescription
# Name of this ptz (can be virtual)
string name
# Limits in degrees on the pan axis
spot_cam/PTZLimits pan_limit
# Limits in degrees on the pan axis
spot_cam/PTZLimits tilt_limit
# Limits in degrees on the pan axis
spot_cam/PTZLimits zoom_limit
================================================================================
MSG: spot_cam/PTZLimits
# https://dev.bostondynamics.com/protos/bosdyn/api/proto_reference#ptzdescription-limits
# If both max and min are zero, this means the limit is unset. The documentation states that if a limit
# is unset, then all positions are valid.
# https://dev.bostondynamics.com/protos/bosdyn/api/proto_reference#ptzdescription
# Minimum value for the axis
float32 min
# Maximum value for the axis
float32 max"""
  __slots__ = ['ptzs']
  _slot_types = ['spot_cam/PTZState[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ptzs

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PTZStateArray, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.ptzs is None:
        self.ptzs = []
    else:
      self.ptzs = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.ptzs)
      buff.write(_struct_I.pack(length))
      for val1 in self.ptzs:
        _v1 = val1.header
        _x = _v1.seq
        buff.write(_get_struct_I().pack(_x))
        _v2 = _v1.stamp
        _x = _v2
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v1.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v3 = val1.ptz
        _x = _v3.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v4 = _v3.pan_limit
        _x = _v4
        buff.write(_get_struct_2f().pack(_x.min, _x.max))
        _v5 = _v3.tilt_limit
        _x = _v5
        buff.write(_get_struct_2f().pack(_x.min, _x.max))
        _v6 = _v3.zoom_limit
        _x = _v6
        buff.write(_get_struct_2f().pack(_x.min, _x.max))
        _x = val1
        buff.write(_get_struct_3f().pack(_x.pan, _x.tilt, _x.zoom))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.ptzs is None:
        self.ptzs = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ptzs = []
      for i in range(0, length):
        val1 = spot_cam.msg.PTZState()
        _v7 = val1.header
        start = end
        end += 4
        (_v7.seq,) = _get_struct_I().unpack(str[start:end])
        _v8 = _v7.stamp
        _x = _v8
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v7.frame_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v7.frame_id = str[start:end]
        _v9 = val1.ptz
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v9.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v9.name = str[start:end]
        _v10 = _v9.pan_limit
        _x = _v10
        start = end
        end += 8
        (_x.min, _x.max,) = _get_struct_2f().unpack(str[start:end])
        _v11 = _v9.tilt_limit
        _x = _v11
        start = end
        end += 8
        (_x.min, _x.max,) = _get_struct_2f().unpack(str[start:end])
        _v12 = _v9.zoom_limit
        _x = _v12
        start = end
        end += 8
        (_x.min, _x.max,) = _get_struct_2f().unpack(str[start:end])
        _x = val1
        start = end
        end += 12
        (_x.pan, _x.tilt, _x.zoom,) = _get_struct_3f().unpack(str[start:end])
        self.ptzs.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.ptzs)
      buff.write(_struct_I.pack(length))
      for val1 in self.ptzs:
        _v13 = val1.header
        _x = _v13.seq
        buff.write(_get_struct_I().pack(_x))
        _v14 = _v13.stamp
        _x = _v14
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v13.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v15 = val1.ptz
        _x = _v15.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v16 = _v15.pan_limit
        _x = _v16
        buff.write(_get_struct_2f().pack(_x.min, _x.max))
        _v17 = _v15.tilt_limit
        _x = _v17
        buff.write(_get_struct_2f().pack(_x.min, _x.max))
        _v18 = _v15.zoom_limit
        _x = _v18
        buff.write(_get_struct_2f().pack(_x.min, _x.max))
        _x = val1
        buff.write(_get_struct_3f().pack(_x.pan, _x.tilt, _x.zoom))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.ptzs is None:
        self.ptzs = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ptzs = []
      for i in range(0, length):
        val1 = spot_cam.msg.PTZState()
        _v19 = val1.header
        start = end
        end += 4
        (_v19.seq,) = _get_struct_I().unpack(str[start:end])
        _v20 = _v19.stamp
        _x = _v20
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v19.frame_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v19.frame_id = str[start:end]
        _v21 = val1.ptz
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v21.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v21.name = str[start:end]
        _v22 = _v21.pan_limit
        _x = _v22
        start = end
        end += 8
        (_x.min, _x.max,) = _get_struct_2f().unpack(str[start:end])
        _v23 = _v21.tilt_limit
        _x = _v23
        start = end
        end += 8
        (_x.min, _x.max,) = _get_struct_2f().unpack(str[start:end])
        _v24 = _v21.zoom_limit
        _x = _v24
        start = end
        end += 8
        (_x.min, _x.max,) = _get_struct_2f().unpack(str[start:end])
        _x = val1
        start = end
        end += 12
        (_x.pan, _x.tilt, _x.zoom,) = _get_struct_3f().unpack(str[start:end])
        self.ptzs.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
