services:
  
  # Container providing the Spot SDK and its dependencies (based on Ubuntu 20.04 LTS)
  spot-sdk:
    extends: # Add config for GUIs and useful terminal properties
      file: ./docker/core-compose.yaml
      service: base-gui

    build:
      context: .
      target: spot-sdk
      args:
        BASE_IMAGE: ubuntu:20.04 # Use a base image without GPU support
        SPOT_SDK_VERSION: 4.1.0 # Specifies the Spot Python package versions
    
    image: bennedh/spot-skills:spot-sdk

    volumes: # Mount this repository into the container (for file access)
      - .:/docker/spot_skills

  # Container providing the Spot SDK alongside ROS 1 Noetic and MoveIt (no NVIDIA GPU)
  spot-moveit:
    extends: # Add config for GUIs and useful terminal properties
      file: ./docker/core-compose.yaml
      service: base-gui

    build:
      context: .
      target: spot-sdk
      args:
        BASE_IMAGE: ubuntu:20.04 # Use a base image without GPU support
        SPOT_SDK_VERSION: 4.1.0 # Specifies the Spot Python package versions

        # Install the Spot SDK onto the stage that has ROS 1 Noetic and MoveIt
        INSTALL_SPOT_SDK_ONTO: noetic-moveit
    
    image: bennedh/spot-skills:spot-moveit

    volumes: # Mount this repository (a ROS workspace) into the container
      - .:/docker/spot_skills

  # Container providing NVIDIA GPU support for Spot SDK, ROS 1 Noetic, and MoveIt
  spot-moveit-gpu:
    extends: # Extend Docker service config for GUIs and NVIDIA GPU(s)
      file: ./docker/core-compose.yaml
      service: nvidia-gpu

    build:
      context: .
      target: spot-sdk
      args:
        SPOT_SDK_VERSION: 4.1.0 # Specifies the Spot Python package versions

        # Install the Spot SDK onto the stage that has ROS 1 Noetic and MoveIt
        INSTALL_SPOT_SDK_ONTO: noetic-moveit
    
    image: bennedh/spot-skills:spot-moveit-gpu

    volumes: # Mount this repository (a ROS workspace) into the container
      - .:/docker/spot_skills

  # Container providing NVIDIA GPU support for Spot SDK, ROS 1 Noetic, and champ
  spot-champ-gpu:
    extends: # Extend Docker service config for GUIs and NVIDIA GPU(s)
      file: ./docker/core-compose.yaml
      service: nvidia-gpu

    build:
      context: .
      target: spot-catkin-deps
      args:
        SPOT_SDK_VERSION: 4.1.0 # Specifies the Spot Python package versions

        # Install the Spot SDK onto the stage that has ROS 1 Noetic and MoveIt
        INSTALL_SPOT_SDK_ONTO: noetic-moveit
    
    image: bennedh/spot-skills:spot-champ-gpu

    volumes: # Mount this repository (a ROS workspace) into the container
      - .:/docker/spot_skills
