services:
  # Service providing a development environment for TAMP-based Spot skills
  spot-tamp-v3.1:
    extends: # Add config for GUIs on Ubuntu host machines
      file: ./docker/ros_docker/compose/core-compose.yaml
      service: base-gui-ubuntu

    build: # Command:   docker compose --progress plain build spot-tamp-v3.1
      context: .
      target: spot-tamp-v3.1

    image: bennedh/spot-skills:spot-tamp-v3.1

    volumes: # Mount this repository (a ROS workspace) into the container
      - .:/docker/spot_skills
