services:

  # This service creates a container running Ubuntu 20.04 with ROS 1 Noetic installed
  noetic-no-gpu:
    extends: # Extend a service providing the config needed to run GUIs from the container
      file: ./docker/gui-compose.yaml
      service: base-gui
    # TODO: Modify the base image, somehow!
    build: .
  
  # This service adds NVIDIA GPU support to our Ubuntu 20.04 and ROS 1 Noetic setup
  noetic-nvidia: # This NVIDIA GPU support
    extends: # Extend a service providing the config needed to run GUIs from the container
      file: ./docker/gui-compose.yaml
      service: base-gui
    build: .
    environment: # Additional NVIDIA-required environment variables
      - NVIDIA_VISIBLE_DEVICES=all # Ensure that the container can access all NVIDIA devices
      - NVIDIA_DRIVER_CAPABILITIES=all # Enable all NVIDIA driver capabilities for container
    network_mode: host # Share the host's network
    deploy:
      resources:
        reservations:   # Host machine must guarantee the container these resources
          devices:
            - driver: nvidia      # NVIDIA-provided driver
              count: all          # Reserve all GPU devices on the host machine
              capabilities: [gpu]
    runtime: nvidia               # Use the NVIDIA Container Runtime
