services:
  # Create a container running Ubuntu 20.04 with ROS 1 Noetic
  noetic-no-gpu:
    extends: # Extend a service providing the config needed to run GUIs from the container
      file: ./docker/core-compose.yaml
      service: base-gui

    build:
      context: .
      target: noetic-moveit
      args:
        BASE_IMAGE: ubuntu:20.04 # Use a CUDA-less base image for the GPU-less service

    volumes:
      - .:/spot_skills # Mount the repository (a ROS workspace) to the container

  # Install the dependencies for the Spot ROS 1 driver alongside ROS 1 Noetic
  spot-ros1-no-gpu:
    extends: # Extend a service providing the config needed to run GUIs from the container
      file: ./docker/core-compose.yaml
      service: base-gui

    build:
      context: .
      target: noetic-moveit-spot-driver
      args:
        BASE_IMAGE: ubuntu:20.04 # Use a CUDA-less base image for the GPU-less service

    volumes:
      - .:/spot_skills # Mount the repository (a ROS workspace) to the container

  # Add NVIDIA GPU support to the Ubuntu 20.04 and ROS 1 Noetic container
  noetic-nvidia:
    extends: # Extend a service providing the config needed for GUIs and NVIDIA GPU(s)
      file: ./docker/core-compose.yaml
      service: nvidia-gpu

    build:
      context: .
      target: noetic-moveit

    volumes:
      - .:/spot_skills # Mount the repository (a ROS workspace) to the container

  # Install the dependencies for the Spot ROS 1 driver alongside NVIDIA GPU support
  spot-ros1:
    extends: # Extend a service providing the config needed for GUIs and NVIDIA GPU(s)
      file: ./docker/core-compose.yaml
      service: nvidia-gpu

    build:
      context: .
      target: noetic-moveit-spot-driver

    volumes:
      - .:/spot_skills # Mount the repository (a ROS workspace) to the container

  # Container with just the Spot SDK and its dependencies
  spot-sdk:
    extends: # Add config for GUIs and useful terminal properties
      file: ./docker/core-compose.yaml
      service: base-gui
    build:
      context: ./docker
      dockerfile: Spot-Dockerfile
      target: spot-sdk
