services:
  # Container running Ubuntu 20.04 LTS with ROS 1 Noetic and MoveIt installed (no GPU support)
  noetic-moveit:
    extends: # Add config for GUIs and useful terminal properties
      file: ./docker/core-compose.yaml
      service: base-gui

    build:
      context: .
      target: noetic-moveit
      args:
        BASE_IMAGE: ubuntu:20.04 # Use a base image without GPU support

    volumes:
      - .:/spot_skills # Mount this repository (a ROS workspace) into the container

  # Container providing NVIDIA GPU support alongside ROS 1 Noetic and MoveIt
  noetic-moveit-gpu:
    extends: # Extend a service providing the config needed for GUIs and NVIDIA GPU(s)
      file: ./docker/core-compose.yaml
      service: nvidia-gpu

    build:
      context: .
      target: noetic-moveit

    volumes:
      - .:/spot_skills # Mount this repository (a ROS workspace) into the container
  
  # Container providing the Spot SDK and its dependencies (based on Ubuntu 20.04 LTS)
  spot-sdk:
    extends: # Add config for GUIs and useful terminal properties
      file: ./docker/core-compose.yaml
      service: base-gui

    build:
      context: .
      target: spot-sdk
      args:
        BASE_IMAGE: ubuntu:20.04 # Use a base image without GPU support
        SPOT_SDK_VERSION: 4.0.3 # Specifies the Spot Python package versions
