[tool.ruff]
# Use the same settings as Black
line-length = 88
indent-width = 4

[tool.ruff.lint]
# Enable Pyflakes (F), pycodestyle errors (E), isort (I), pep8-naming (N),
# pydocstyle (D), pyupgrade (UP), flake8-annotations (ANN), flake8-bandit (S),
# flake8-bugbear (B), flake8-builtins (A), flake8-comprehensions (C4),
# flake8-pytest-style (PT), flake8-use-pathlib (PTH), Pylint (PL),
# tryceratops (TRY), NumPy-specific (NPY), pydoclint (DOC), and Ruff (RUF).
select = [
    "F",
    "E",
    "I",
    "N",
    "D",
    "UP",
    "ANN",
    "S",
    "B",
    "A",
    "C4",
    "PT",
    "PTH",
    "PL",
    "TRY",
    "NPY",
    "DOC",
    "RUF",
]
ignore = ["ANN101"] # Ignore type annotations on `self`
unfixable = ["F401"] # Disable fix for unused imports

[tool.ruff.format]
# Like Black, use double quotes for strings
quote-style = "double"

# Like Black, indent with spaces (not tabs)
indent-style = "space"
