# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from spot_msgs/ParentEdge.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class ParentEdge(genpy.Message):
  _md5sum = "14b32cd1337d19fdeb4701a1cb7d7dd2"
  _type = "spot_msgs/ParentEdge"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string parent_frame_name
geometry_msgs/Pose parent_tform_child
================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['parent_frame_name','parent_tform_child']
  _slot_types = ['string','geometry_msgs/Pose']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       parent_frame_name,parent_tform_child

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ParentEdge, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.parent_frame_name is None:
        self.parent_frame_name = ''
      if self.parent_tform_child is None:
        self.parent_tform_child = geometry_msgs.msg.Pose()
    else:
      self.parent_frame_name = ''
      self.parent_tform_child = geometry_msgs.msg.Pose()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.parent_frame_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.parent_tform_child.position.x, _x.parent_tform_child.position.y, _x.parent_tform_child.position.z, _x.parent_tform_child.orientation.x, _x.parent_tform_child.orientation.y, _x.parent_tform_child.orientation.z, _x.parent_tform_child.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.parent_tform_child is None:
        self.parent_tform_child = geometry_msgs.msg.Pose()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.parent_frame_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.parent_frame_name = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.parent_tform_child.position.x, _x.parent_tform_child.position.y, _x.parent_tform_child.position.z, _x.parent_tform_child.orientation.x, _x.parent_tform_child.orientation.y, _x.parent_tform_child.orientation.z, _x.parent_tform_child.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.parent_frame_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.parent_tform_child.position.x, _x.parent_tform_child.position.y, _x.parent_tform_child.position.z, _x.parent_tform_child.orientation.x, _x.parent_tform_child.orientation.y, _x.parent_tform_child.orientation.z, _x.parent_tform_child.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.parent_tform_child is None:
        self.parent_tform_child = geometry_msgs.msg.Pose()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.parent_frame_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.parent_frame_name = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.parent_tform_child.position.x, _x.parent_tform_child.position.y, _x.parent_tform_child.position.z, _x.parent_tform_child.orientation.x, _x.parent_tform_child.orientation.y, _x.parent_tform_child.orientation.z, _x.parent_tform_child.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
