# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from spot_msgs/PoseBodyGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class PoseBodyGoal(genpy.Message):
  _md5sum = "2aaa468be31e97608ddb9e68aa66e756"
  _type = "spot_msgs/PoseBodyGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# The pose the body should be moved to. Only the orientation and the z component (body height) of position is considered.
# If this is unset, the rpy/body height values will be used instead.
geometry_msgs/Pose body_pose

# Alternative specification of the body pose with rpy (in degrees). These values are ignored if the body_pose is set
int8 roll
int8 pitch
int8 yaw
float32 body_height

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['body_pose','roll','pitch','yaw','body_height']
  _slot_types = ['geometry_msgs/Pose','int8','int8','int8','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       body_pose,roll,pitch,yaw,body_height

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PoseBodyGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.body_pose is None:
        self.body_pose = geometry_msgs.msg.Pose()
      if self.roll is None:
        self.roll = 0
      if self.pitch is None:
        self.pitch = 0
      if self.yaw is None:
        self.yaw = 0
      if self.body_height is None:
        self.body_height = 0.
    else:
      self.body_pose = geometry_msgs.msg.Pose()
      self.roll = 0
      self.pitch = 0
      self.yaw = 0
      self.body_height = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7d3bf().pack(_x.body_pose.position.x, _x.body_pose.position.y, _x.body_pose.position.z, _x.body_pose.orientation.x, _x.body_pose.orientation.y, _x.body_pose.orientation.z, _x.body_pose.orientation.w, _x.roll, _x.pitch, _x.yaw, _x.body_height))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.body_pose is None:
        self.body_pose = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 63
      (_x.body_pose.position.x, _x.body_pose.position.y, _x.body_pose.position.z, _x.body_pose.orientation.x, _x.body_pose.orientation.y, _x.body_pose.orientation.z, _x.body_pose.orientation.w, _x.roll, _x.pitch, _x.yaw, _x.body_height,) = _get_struct_7d3bf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7d3bf().pack(_x.body_pose.position.x, _x.body_pose.position.y, _x.body_pose.position.z, _x.body_pose.orientation.x, _x.body_pose.orientation.y, _x.body_pose.orientation.z, _x.body_pose.orientation.w, _x.roll, _x.pitch, _x.yaw, _x.body_height))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.body_pose is None:
        self.body_pose = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 63
      (_x.body_pose.position.x, _x.body_pose.position.y, _x.body_pose.position.z, _x.body_pose.orientation.x, _x.body_pose.orientation.y, _x.body_pose.orientation.z, _x.body_pose.orientation.w, _x.roll, _x.pitch, _x.yaw, _x.body_height,) = _get_struct_7d3bf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7d3bf = None
def _get_struct_7d3bf():
    global _struct_7d3bf
    if _struct_7d3bf is None:
        _struct_7d3bf = struct.Struct("<7d3bf")
    return _struct_7d3bf
