# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from spot_msgs/SpotCheckLoadCell.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SpotCheckLoadCell(genpy.Message):
  _md5sum = "bfb62ba66777d3800f98e3fc7140667a"
  _type = "spot_msgs/SpotCheckLoadCell"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 ERROR_UNKNOWN = 0              # Unused enum.
uint8 ERROR_NONE = 1                 # No hardware error detected.
uint8 ERROR_ZERO_OUT_OF_RANGE = 2    # Load cell calibration failure.

# The loadcell error code
uint8 error
# The current loadcell zero as fraction of full range [0-1]
float32 zero
# The previous loadcell zero as fraction of full range [0-1]
float32 old_zero"""
  # Pseudo-constants
  ERROR_UNKNOWN = 0
  ERROR_NONE = 1
  ERROR_ZERO_OUT_OF_RANGE = 2

  __slots__ = ['error','zero','old_zero']
  _slot_types = ['uint8','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       error,zero,old_zero

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SpotCheckLoadCell, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.error is None:
        self.error = 0
      if self.zero is None:
        self.zero = 0.
      if self.old_zero is None:
        self.old_zero = 0.
    else:
      self.error = 0
      self.zero = 0.
      self.old_zero = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B2f().pack(_x.error, _x.zero, _x.old_zero))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.error, _x.zero, _x.old_zero,) = _get_struct_B2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B2f().pack(_x.error, _x.zero, _x.old_zero))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.error, _x.zero, _x.old_zero,) = _get_struct_B2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B2f = None
def _get_struct_B2f():
    global _struct_B2f
    if _struct_B2f is None:
        _struct_B2f = struct.Struct("<B2f")
    return _struct_B2f
