// Generated by gencpp from file spot_msgs/DockFeedback.msg
// DO NOT EDIT!


#ifndef SPOT_MSGS_MESSAGE_DOCKFEEDBACK_H
#define SPOT_MSGS_MESSAGE_DOCKFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <spot_msgs/DockState.h>

namespace spot_msgs
{
template <class ContainerAllocator>
struct DockFeedback_
{
  typedef DockFeedback_<ContainerAllocator> Type;

  DockFeedback_()
    : status()  {
    }
  DockFeedback_(const ContainerAllocator& _alloc)
    : status(_alloc)  {
  (void)_alloc;
    }



   typedef  ::spot_msgs::DockState_<ContainerAllocator>  _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::spot_msgs::DockFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spot_msgs::DockFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct DockFeedback_

typedef ::spot_msgs::DockFeedback_<std::allocator<void> > DockFeedback;

typedef boost::shared_ptr< ::spot_msgs::DockFeedback > DockFeedbackPtr;
typedef boost::shared_ptr< ::spot_msgs::DockFeedback const> DockFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spot_msgs::DockFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spot_msgs::DockFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::spot_msgs::DockFeedback_<ContainerAllocator1> & lhs, const ::spot_msgs::DockFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::spot_msgs::DockFeedback_<ContainerAllocator1> & lhs, const ::spot_msgs::DockFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace spot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::spot_msgs::DockFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spot_msgs::DockFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spot_msgs::DockFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spot_msgs::DockFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_msgs::DockFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_msgs::DockFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spot_msgs::DockFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c362c4f04a7060b16832e7c8aadb5896";
  }

  static const char* value(const ::spot_msgs::DockFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc362c4f04a7060b1ULL;
  static const uint64_t static_value2 = 0x6832e7c8aadb5896ULL;
};

template<class ContainerAllocator>
struct DataType< ::spot_msgs::DockFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spot_msgs/DockFeedback";
  }

  static const char* value(const ::spot_msgs::DockFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spot_msgs::DockFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"DockState status\n"
"\n"
"================================================================================\n"
"MSG: spot_msgs/DockState\n"
"# Status\n"
"uint8 DOCK_STATUS_UNKNOWN = 0\n"
"uint8 DOCK_STATUS_DOCKED = 1\n"
"uint8 DOCK_STATUS_DOCKING = 2\n"
"uint8 DOCK_STATUS_UNDOCKED = 3\n"
"uint8 DOCK_STATUS_UNDOCKING = 4\n"
"\n"
"# DockType\n"
"uint8 DOCK_TYPE_UNKNOWN = 0\n"
"uint8 DOCK_TYPE_CONTACT_PROTOTYPE = 2\n"
"uint8 DOCK_TYPE_SPOT_DOCK = 3\n"
"\n"
"# LinkStatus\n"
"uint8 LINK_STATUS_UNKNOWN = 0\n"
"uint8 LINK_STATUS_CONNECTED = 1\n"
"uint8 LINK_STATUS_ERROR = 2\n"
"uint8 LINK_STATUS_DETECTING = 3\n"
"\n"
"uint8 status\n"
"uint8 dock_type\n"
"uint32 dock_id\n"
"uint8 power_status\n"
;
  }

  static const char* value(const ::spot_msgs::DockFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spot_msgs::DockFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DockFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spot_msgs::DockFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spot_msgs::DockFeedback_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    s << std::endl;
    Printer< ::spot_msgs::DockState_<ContainerAllocator> >::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPOT_MSGS_MESSAGE_DOCKFEEDBACK_H
