// Generated by gencpp from file spot_msgs/Dock.msg
// DO NOT EDIT!


#ifndef SPOT_MSGS_MESSAGE_DOCK_H
#define SPOT_MSGS_MESSAGE_DOCK_H

#include <ros/service_traits.h>


#include <spot_msgs/DockRequest.h>
#include <spot_msgs/DockResponse.h>


namespace spot_msgs
{

struct Dock
{

typedef DockRequest Request;
typedef DockResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Dock
} // namespace spot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::spot_msgs::Dock > {
  static const char* value()
  {
    return "c1102efdad60fe70c4c44187beb3e1e8";
  }

  static const char* value(const ::spot_msgs::Dock&) { return value(); }
};

template<>
struct DataType< ::spot_msgs::Dock > {
  static const char* value()
  {
    return "spot_msgs/Dock";
  }

  static const char* value(const ::spot_msgs::Dock&) { return value(); }
};


// service_traits::MD5Sum< ::spot_msgs::DockRequest> should match
// service_traits::MD5Sum< ::spot_msgs::Dock >
template<>
struct MD5Sum< ::spot_msgs::DockRequest>
{
  static const char* value()
  {
    return MD5Sum< ::spot_msgs::Dock >::value();
  }
  static const char* value(const ::spot_msgs::DockRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::spot_msgs::DockRequest> should match
// service_traits::DataType< ::spot_msgs::Dock >
template<>
struct DataType< ::spot_msgs::DockRequest>
{
  static const char* value()
  {
    return DataType< ::spot_msgs::Dock >::value();
  }
  static const char* value(const ::spot_msgs::DockRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::spot_msgs::DockResponse> should match
// service_traits::MD5Sum< ::spot_msgs::Dock >
template<>
struct MD5Sum< ::spot_msgs::DockResponse>
{
  static const char* value()
  {
    return MD5Sum< ::spot_msgs::Dock >::value();
  }
  static const char* value(const ::spot_msgs::DockResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::spot_msgs::DockResponse> should match
// service_traits::DataType< ::spot_msgs::Dock >
template<>
struct DataType< ::spot_msgs::DockResponse>
{
  static const char* value()
  {
    return DataType< ::spot_msgs::Dock >::value();
  }
  static const char* value(const ::spot_msgs::DockResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SPOT_MSGS_MESSAGE_DOCK_H
