// Generated by gencpp from file spot_msgs/DownloadGraph.msg
// DO NOT EDIT!


#ifndef SPOT_MSGS_MESSAGE_DOWNLOADGRAPH_H
#define SPOT_MSGS_MESSAGE_DOWNLOADGRAPH_H

#include <ros/service_traits.h>


#include <spot_msgs/DownloadGraphRequest.h>
#include <spot_msgs/DownloadGraphResponse.h>


namespace spot_msgs
{

struct DownloadGraph
{

typedef DownloadGraphRequest Request;
typedef DownloadGraphResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DownloadGraph
} // namespace spot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::spot_msgs::DownloadGraph > {
  static const char* value()
  {
    return "a39595a31eb3fe78c31f978ce5465539";
  }

  static const char* value(const ::spot_msgs::DownloadGraph&) { return value(); }
};

template<>
struct DataType< ::spot_msgs::DownloadGraph > {
  static const char* value()
  {
    return "spot_msgs/DownloadGraph";
  }

  static const char* value(const ::spot_msgs::DownloadGraph&) { return value(); }
};


// service_traits::MD5Sum< ::spot_msgs::DownloadGraphRequest> should match
// service_traits::MD5Sum< ::spot_msgs::DownloadGraph >
template<>
struct MD5Sum< ::spot_msgs::DownloadGraphRequest>
{
  static const char* value()
  {
    return MD5Sum< ::spot_msgs::DownloadGraph >::value();
  }
  static const char* value(const ::spot_msgs::DownloadGraphRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::spot_msgs::DownloadGraphRequest> should match
// service_traits::DataType< ::spot_msgs::DownloadGraph >
template<>
struct DataType< ::spot_msgs::DownloadGraphRequest>
{
  static const char* value()
  {
    return DataType< ::spot_msgs::DownloadGraph >::value();
  }
  static const char* value(const ::spot_msgs::DownloadGraphRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::spot_msgs::DownloadGraphResponse> should match
// service_traits::MD5Sum< ::spot_msgs::DownloadGraph >
template<>
struct MD5Sum< ::spot_msgs::DownloadGraphResponse>
{
  static const char* value()
  {
    return MD5Sum< ::spot_msgs::DownloadGraph >::value();
  }
  static const char* value(const ::spot_msgs::DownloadGraphResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::spot_msgs::DownloadGraphResponse> should match
// service_traits::DataType< ::spot_msgs::DownloadGraph >
template<>
struct DataType< ::spot_msgs::DownloadGraphResponse>
{
  static const char* value()
  {
    return DataType< ::spot_msgs::DownloadGraph >::value();
  }
  static const char* value(const ::spot_msgs::DownloadGraphResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SPOT_MSGS_MESSAGE_DOWNLOADGRAPH_H
