// Generated by gencpp from file spot_msgs/NavigateInit.msg
// DO NOT EDIT!


#ifndef SPOT_MSGS_MESSAGE_NAVIGATEINIT_H
#define SPOT_MSGS_MESSAGE_NAVIGATEINIT_H

#include <ros/service_traits.h>


#include <spot_msgs/NavigateInitRequest.h>
#include <spot_msgs/NavigateInitResponse.h>


namespace spot_msgs
{

struct NavigateInit
{

typedef NavigateInitRequest Request;
typedef NavigateInitResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NavigateInit
} // namespace spot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::spot_msgs::NavigateInit > {
  static const char* value()
  {
    return "c444c9070e6d223b1750275fad5b1484";
  }

  static const char* value(const ::spot_msgs::NavigateInit&) { return value(); }
};

template<>
struct DataType< ::spot_msgs::NavigateInit > {
  static const char* value()
  {
    return "spot_msgs/NavigateInit";
  }

  static const char* value(const ::spot_msgs::NavigateInit&) { return value(); }
};


// service_traits::MD5Sum< ::spot_msgs::NavigateInitRequest> should match
// service_traits::MD5Sum< ::spot_msgs::NavigateInit >
template<>
struct MD5Sum< ::spot_msgs::NavigateInitRequest>
{
  static const char* value()
  {
    return MD5Sum< ::spot_msgs::NavigateInit >::value();
  }
  static const char* value(const ::spot_msgs::NavigateInitRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::spot_msgs::NavigateInitRequest> should match
// service_traits::DataType< ::spot_msgs::NavigateInit >
template<>
struct DataType< ::spot_msgs::NavigateInitRequest>
{
  static const char* value()
  {
    return DataType< ::spot_msgs::NavigateInit >::value();
  }
  static const char* value(const ::spot_msgs::NavigateInitRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::spot_msgs::NavigateInitResponse> should match
// service_traits::MD5Sum< ::spot_msgs::NavigateInit >
template<>
struct MD5Sum< ::spot_msgs::NavigateInitResponse>
{
  static const char* value()
  {
    return MD5Sum< ::spot_msgs::NavigateInit >::value();
  }
  static const char* value(const ::spot_msgs::NavigateInitResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::spot_msgs::NavigateInitResponse> should match
// service_traits::DataType< ::spot_msgs::NavigateInit >
template<>
struct DataType< ::spot_msgs::NavigateInitResponse>
{
  static const char* value()
  {
    return DataType< ::spot_msgs::NavigateInit >::value();
  }
  static const char* value(const ::spot_msgs::NavigateInitResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SPOT_MSGS_MESSAGE_NAVIGATEINIT_H
