// Generated by gencpp from file spot_msgs/SetTerrainParams.msg
// DO NOT EDIT!


#ifndef SPOT_MSGS_MESSAGE_SETTERRAINPARAMS_H
#define SPOT_MSGS_MESSAGE_SETTERRAINPARAMS_H

#include <ros/service_traits.h>


#include <spot_msgs/SetTerrainParamsRequest.h>
#include <spot_msgs/SetTerrainParamsResponse.h>


namespace spot_msgs
{

struct SetTerrainParams
{

typedef SetTerrainParamsRequest Request;
typedef SetTerrainParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTerrainParams
} // namespace spot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::spot_msgs::SetTerrainParams > {
  static const char* value()
  {
    return "7ab3f769faaa7a5562cf1f71a78cd453";
  }

  static const char* value(const ::spot_msgs::SetTerrainParams&) { return value(); }
};

template<>
struct DataType< ::spot_msgs::SetTerrainParams > {
  static const char* value()
  {
    return "spot_msgs/SetTerrainParams";
  }

  static const char* value(const ::spot_msgs::SetTerrainParams&) { return value(); }
};


// service_traits::MD5Sum< ::spot_msgs::SetTerrainParamsRequest> should match
// service_traits::MD5Sum< ::spot_msgs::SetTerrainParams >
template<>
struct MD5Sum< ::spot_msgs::SetTerrainParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::spot_msgs::SetTerrainParams >::value();
  }
  static const char* value(const ::spot_msgs::SetTerrainParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::spot_msgs::SetTerrainParamsRequest> should match
// service_traits::DataType< ::spot_msgs::SetTerrainParams >
template<>
struct DataType< ::spot_msgs::SetTerrainParamsRequest>
{
  static const char* value()
  {
    return DataType< ::spot_msgs::SetTerrainParams >::value();
  }
  static const char* value(const ::spot_msgs::SetTerrainParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::spot_msgs::SetTerrainParamsResponse> should match
// service_traits::MD5Sum< ::spot_msgs::SetTerrainParams >
template<>
struct MD5Sum< ::spot_msgs::SetTerrainParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::spot_msgs::SetTerrainParams >::value();
  }
  static const char* value(const ::spot_msgs::SetTerrainParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::spot_msgs::SetTerrainParamsResponse> should match
// service_traits::DataType< ::spot_msgs::SetTerrainParams >
template<>
struct DataType< ::spot_msgs::SetTerrainParamsResponse>
{
  static const char* value()
  {
    return DataType< ::spot_msgs::SetTerrainParams >::value();
  }
  static const char* value(const ::spot_msgs::SetTerrainParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SPOT_MSGS_MESSAGE_SETTERRAINPARAMS_H
