services:
  # This base service defines the configuration needed to support GUIs from the container
  base-gui:
    environment:

      # Environment variables to support in-container GUIs
      - DISPLAY # Pass the DISPLAY environment variable for X11 forwarding
      - QT_X11_NO_MITSHM=1 # Prevent Qt apps in the container from using X11's MIT-SHM extension

      # Nice-to-have environment variables for other useful settings
      - TERM # Pass the TERM environment variable specifying the terminal type
      - color_prompt=yes # Provide a colored prompt in the container
    
    devices:
      - "/dev/dri:/dev/dri" # Map the host's Direct Rendering Infrastructure (DRI) into the container

    volumes:
      - .:/spot_skills # Mount the current directory (in this project, a ROS workspace)
      - /tmp/.X11-unix:/tmp/.X11-unix # Mount the X11 Unix socket to support GUIs
      - /etc/localtime:/etc/localtime:ro # Sync the container's timezone with the host (read-only)
    
    stdin_open: true    # docker run -i
    tty: true           # docker run -t
