# Docker Compose configurations no longer in use (but not useless, hence not deleted)

services:
  # Container running Ubuntu 20.04 LTS with ROS 1 Noetic and MoveIt installed (no GPU support)
  noetic-moveit:
    extends: # Add config for GUIs and useful terminal properties
      file: ./docker/core-compose.yaml
      service: base-gui

    build:
      context: .
      target: noetic-moveit
      args:
        BASE_IMAGE: ubuntu:20.04 # Use a base image without GPU support

    image: bennedh/spot-skills:noetic-moveit

    volumes: # Mount this repository (a ROS workspace) into the container
      - .:/docker/spot_skills

  # Container providing NVIDIA GPU support alongside ROS 1 Noetic and MoveIt
  noetic-moveit-gpu:
    extends: # Extend Docker service config for GUIs and NVIDIA GPU(s)
      file: ./docker/core-compose.yaml
      service: nvidia-gpu

    build:
      context: .
      target: noetic-moveit

    image: bennedh/spot-skills:noetic-moveit-gpu

    volumes: # Mount this repository (a ROS workspace) into the container
      - .:/docker/spot_skills
