// Generated by gencpp from file spot_cam/LookAtPoint.msg
// DO NOT EDIT!


#ifndef SPOT_CAM_MESSAGE_LOOKATPOINT_H
#define SPOT_CAM_MESSAGE_LOOKATPOINT_H

#include <ros/service_traits.h>


#include <spot_cam/LookAtPointRequest.h>
#include <spot_cam/LookAtPointResponse.h>


namespace spot_cam
{

struct LookAtPoint
{

typedef LookAtPointRequest Request;
typedef LookAtPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LookAtPoint
} // namespace spot_cam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::spot_cam::LookAtPoint > {
  static const char* value()
  {
    return "0dc127af1bc4082ad4ce1ba11dbd2e9b";
  }

  static const char* value(const ::spot_cam::LookAtPoint&) { return value(); }
};

template<>
struct DataType< ::spot_cam::LookAtPoint > {
  static const char* value()
  {
    return "spot_cam/LookAtPoint";
  }

  static const char* value(const ::spot_cam::LookAtPoint&) { return value(); }
};


// service_traits::MD5Sum< ::spot_cam::LookAtPointRequest> should match
// service_traits::MD5Sum< ::spot_cam::LookAtPoint >
template<>
struct MD5Sum< ::spot_cam::LookAtPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::spot_cam::LookAtPoint >::value();
  }
  static const char* value(const ::spot_cam::LookAtPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::spot_cam::LookAtPointRequest> should match
// service_traits::DataType< ::spot_cam::LookAtPoint >
template<>
struct DataType< ::spot_cam::LookAtPointRequest>
{
  static const char* value()
  {
    return DataType< ::spot_cam::LookAtPoint >::value();
  }
  static const char* value(const ::spot_cam::LookAtPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::spot_cam::LookAtPointResponse> should match
// service_traits::MD5Sum< ::spot_cam::LookAtPoint >
template<>
struct MD5Sum< ::spot_cam::LookAtPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::spot_cam::LookAtPoint >::value();
  }
  static const char* value(const ::spot_cam::LookAtPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::spot_cam::LookAtPointResponse> should match
// service_traits::DataType< ::spot_cam::LookAtPoint >
template<>
struct DataType< ::spot_cam::LookAtPointResponse>
{
  static const char* value()
  {
    return DataType< ::spot_cam::LookAtPoint >::value();
  }
  static const char* value(const ::spot_cam::LookAtPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SPOT_CAM_MESSAGE_LOOKATPOINT_H
