// Generated by gencpp from file spot_cam/PlaySound.msg
// DO NOT EDIT!


#ifndef SPOT_CAM_MESSAGE_PLAYSOUND_H
#define SPOT_CAM_MESSAGE_PLAYSOUND_H

#include <ros/service_traits.h>


#include <spot_cam/PlaySoundRequest.h>
#include <spot_cam/PlaySoundResponse.h>


namespace spot_cam
{

struct PlaySound
{

typedef PlaySoundRequest Request;
typedef PlaySoundResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlaySound
} // namespace spot_cam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::spot_cam::PlaySound > {
  static const char* value()
  {
    return "2fa7527a0fde73dd5206e9498d885ad7";
  }

  static const char* value(const ::spot_cam::PlaySound&) { return value(); }
};

template<>
struct DataType< ::spot_cam::PlaySound > {
  static const char* value()
  {
    return "spot_cam/PlaySound";
  }

  static const char* value(const ::spot_cam::PlaySound&) { return value(); }
};


// service_traits::MD5Sum< ::spot_cam::PlaySoundRequest> should match
// service_traits::MD5Sum< ::spot_cam::PlaySound >
template<>
struct MD5Sum< ::spot_cam::PlaySoundRequest>
{
  static const char* value()
  {
    return MD5Sum< ::spot_cam::PlaySound >::value();
  }
  static const char* value(const ::spot_cam::PlaySoundRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::spot_cam::PlaySoundRequest> should match
// service_traits::DataType< ::spot_cam::PlaySound >
template<>
struct DataType< ::spot_cam::PlaySoundRequest>
{
  static const char* value()
  {
    return DataType< ::spot_cam::PlaySound >::value();
  }
  static const char* value(const ::spot_cam::PlaySoundRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::spot_cam::PlaySoundResponse> should match
// service_traits::MD5Sum< ::spot_cam::PlaySound >
template<>
struct MD5Sum< ::spot_cam::PlaySoundResponse>
{
  static const char* value()
  {
    return MD5Sum< ::spot_cam::PlaySound >::value();
  }
  static const char* value(const ::spot_cam::PlaySoundResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::spot_cam::PlaySoundResponse> should match
// service_traits::DataType< ::spot_cam::PlaySound >
template<>
struct DataType< ::spot_cam::PlaySoundResponse>
{
  static const char* value()
  {
    return DataType< ::spot_cam::PlaySound >::value();
  }
  static const char* value(const ::spot_cam::PlaySoundResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SPOT_CAM_MESSAGE_PLAYSOUND_H
