// Generated by gencpp from file spot_cam/PlaySoundRequest.msg
// DO NOT EDIT!


#ifndef SPOT_CAM_MESSAGE_PLAYSOUNDREQUEST_H
#define SPOT_CAM_MESSAGE_PLAYSOUNDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace spot_cam
{
template <class ContainerAllocator>
struct PlaySoundRequest_
{
  typedef PlaySoundRequest_<ContainerAllocator> Type;

  PlaySoundRequest_()
    : name()
    , gain(0.0)  {
    }
  PlaySoundRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , gain(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef float _gain_type;
  _gain_type gain;





  typedef boost::shared_ptr< ::spot_cam::PlaySoundRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spot_cam::PlaySoundRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PlaySoundRequest_

typedef ::spot_cam::PlaySoundRequest_<std::allocator<void> > PlaySoundRequest;

typedef boost::shared_ptr< ::spot_cam::PlaySoundRequest > PlaySoundRequestPtr;
typedef boost::shared_ptr< ::spot_cam::PlaySoundRequest const> PlaySoundRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spot_cam::PlaySoundRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spot_cam::PlaySoundRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::spot_cam::PlaySoundRequest_<ContainerAllocator1> & lhs, const ::spot_cam::PlaySoundRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.gain == rhs.gain;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::spot_cam::PlaySoundRequest_<ContainerAllocator1> & lhs, const ::spot_cam::PlaySoundRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace spot_cam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::spot_cam::PlaySoundRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spot_cam::PlaySoundRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spot_cam::PlaySoundRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spot_cam::PlaySoundRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_cam::PlaySoundRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_cam::PlaySoundRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spot_cam::PlaySoundRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "777dadb4aaeef32b67c7a32870799a43";
  }

  static const char* value(const ::spot_cam::PlaySoundRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x777dadb4aaeef32bULL;
  static const uint64_t static_value2 = 0x67c7a32870799a43ULL;
};

template<class ContainerAllocator>
struct DataType< ::spot_cam::PlaySoundRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spot_cam/PlaySoundRequest";
  }

  static const char* value(const ::spot_cam::PlaySoundRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spot_cam::PlaySoundRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Name of the sound to play\n"
"string name\n"
"# Multiplier on the sound volume\n"
"float32 gain\n"
;
  }

  static const char* value(const ::spot_cam::PlaySoundRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spot_cam::PlaySoundRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.gain);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlaySoundRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spot_cam::PlaySoundRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spot_cam::PlaySoundRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "gain: ";
    Printer<float>::stream(s, indent + "  ", v.gain);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPOT_CAM_MESSAGE_PLAYSOUNDREQUEST_H
