// Generated by gencpp from file spot_cam/SetPTZStateRequest.msg
// DO NOT EDIT!


#ifndef SPOT_CAM_MESSAGE_SETPTZSTATEREQUEST_H
#define SPOT_CAM_MESSAGE_SETPTZSTATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <spot_cam/PTZState.h>

namespace spot_cam
{
template <class ContainerAllocator>
struct SetPTZStateRequest_
{
  typedef SetPTZStateRequest_<ContainerAllocator> Type;

  SetPTZStateRequest_()
    : command()  {
    }
  SetPTZStateRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)  {
  (void)_alloc;
    }



   typedef  ::spot_cam::PTZState_<ContainerAllocator>  _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::spot_cam::SetPTZStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spot_cam::SetPTZStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetPTZStateRequest_

typedef ::spot_cam::SetPTZStateRequest_<std::allocator<void> > SetPTZStateRequest;

typedef boost::shared_ptr< ::spot_cam::SetPTZStateRequest > SetPTZStateRequestPtr;
typedef boost::shared_ptr< ::spot_cam::SetPTZStateRequest const> SetPTZStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spot_cam::SetPTZStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spot_cam::SetPTZStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::spot_cam::SetPTZStateRequest_<ContainerAllocator1> & lhs, const ::spot_cam::SetPTZStateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::spot_cam::SetPTZStateRequest_<ContainerAllocator1> & lhs, const ::spot_cam::SetPTZStateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace spot_cam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::spot_cam::SetPTZStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spot_cam::SetPTZStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spot_cam::SetPTZStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spot_cam::SetPTZStateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_cam::SetPTZStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_cam::SetPTZStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spot_cam::SetPTZStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e08053b336ca453cbb59f5d2035c7110";
  }

  static const char* value(const ::spot_cam::SetPTZStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe08053b336ca453cULL;
  static const uint64_t static_value2 = 0xbb59f5d2035c7110ULL;
};

template<class ContainerAllocator>
struct DataType< ::spot_cam::SetPTZStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spot_cam/SetPTZStateRequest";
  }

  static const char* value(const ::spot_cam::SetPTZStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spot_cam::SetPTZStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message can be used to send either position or velocity commands\n"
"# The description of the ptz does not need to be complete - only the name is used\n"
"spot_cam/PTZState command\n"
"\n"
"================================================================================\n"
"MSG: spot_cam/PTZState\n"
"# This message covers two different types which have the exact same field names, to reduce duplication. Depending on the topic,\n"
"# The meaning of the pan/tilt/zoom values changes.\n"
"# https://dev.bostondynamics.com/protos/bosdyn/api/proto_reference#ptzposition\n"
"# https://dev.bostondynamics.com/protos/bosdyn/api/proto_reference#ptzvelocity\n"
"std_msgs/Header header\n"
"# Description of the ptz\n"
"spot_cam/PTZDescription ptz\n"
"# degrees or degrees per second\n"
"float32 pan\n"
"# degrees or degrees per second\n"
"float32 tilt\n"
"# zoom level or zoom level per second\n"
"float32 zoom\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: spot_cam/PTZDescription\n"
"# https://dev.bostondynamics.com/protos/bosdyn/api/proto_reference#ptzdescription\n"
"# Name of this ptz (can be virtual)\n"
"string name\n"
"# Limits in degrees on the pan axis\n"
"spot_cam/PTZLimits pan_limit\n"
"# Limits in degrees on the pan axis\n"
"spot_cam/PTZLimits tilt_limit\n"
"# Limits in degrees on the pan axis\n"
"spot_cam/PTZLimits zoom_limit\n"
"================================================================================\n"
"MSG: spot_cam/PTZLimits\n"
"# https://dev.bostondynamics.com/protos/bosdyn/api/proto_reference#ptzdescription-limits\n"
"# If both max and min are zero, this means the limit is unset. The documentation states that if a limit\n"
"# is unset, then all positions are valid.\n"
"# https://dev.bostondynamics.com/protos/bosdyn/api/proto_reference#ptzdescription\n"
"# Minimum value for the axis\n"
"float32 min\n"
"# Maximum value for the axis\n"
"float32 max\n"
;
  }

  static const char* value(const ::spot_cam::SetPTZStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spot_cam::SetPTZStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPTZStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spot_cam::SetPTZStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spot_cam::SetPTZStateRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    s << std::endl;
    Printer< ::spot_cam::PTZState_<ContainerAllocator> >::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPOT_CAM_MESSAGE_SETPTZSTATEREQUEST_H
