// Generated by gencpp from file spot_cam/SetString.msg
// DO NOT EDIT!


#ifndef SPOT_CAM_MESSAGE_SETSTRING_H
#define SPOT_CAM_MESSAGE_SETSTRING_H

#include <ros/service_traits.h>


#include <spot_cam/SetStringRequest.h>
#include <spot_cam/SetStringResponse.h>


namespace spot_cam
{

struct SetString
{

typedef SetStringRequest Request;
typedef SetStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetString
} // namespace spot_cam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::spot_cam::SetString > {
  static const char* value()
  {
    return "43ad6a9b380ac342e4b20e501a2fd46c";
  }

  static const char* value(const ::spot_cam::SetString&) { return value(); }
};

template<>
struct DataType< ::spot_cam::SetString > {
  static const char* value()
  {
    return "spot_cam/SetString";
  }

  static const char* value(const ::spot_cam::SetString&) { return value(); }
};


// service_traits::MD5Sum< ::spot_cam::SetStringRequest> should match
// service_traits::MD5Sum< ::spot_cam::SetString >
template<>
struct MD5Sum< ::spot_cam::SetStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::spot_cam::SetString >::value();
  }
  static const char* value(const ::spot_cam::SetStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::spot_cam::SetStringRequest> should match
// service_traits::DataType< ::spot_cam::SetString >
template<>
struct DataType< ::spot_cam::SetStringRequest>
{
  static const char* value()
  {
    return DataType< ::spot_cam::SetString >::value();
  }
  static const char* value(const ::spot_cam::SetStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::spot_cam::SetStringResponse> should match
// service_traits::MD5Sum< ::spot_cam::SetString >
template<>
struct MD5Sum< ::spot_cam::SetStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::spot_cam::SetString >::value();
  }
  static const char* value(const ::spot_cam::SetStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::spot_cam::SetStringResponse> should match
// service_traits::DataType< ::spot_cam::SetString >
template<>
struct DataType< ::spot_cam::SetStringResponse>
{
  static const char* value()
  {
    return DataType< ::spot_cam::SetString >::value();
  }
  static const char* value(const ::spot_cam::SetStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SPOT_CAM_MESSAGE_SETSTRING_H
