# Specify AprilTag-to-object relative transforms, tag sizes, and which cameras detect which tag sizes
tags:
  tag_51:
    tag_size_cm: 18.5
    relative_frames:
      whiteboard: [0, 0, 0, 0, 0, 0]

  tag_50:
    tag_size_cm: 18.5
    relative_frames:
      eraser: [0, -0.2243, 0.141, 0, 0, 0]
      cabinet: [0, -0.3843, 0.141, 0, 0, 0] # TODO: Check this guess!

cameras:
  frontleft:
    recognized_tag_sizes_cm: [18.5]
    detects_single_tags: True
    detects_bundles: False
  frontright:
    recognized_tag_sizes_cm: [18.5]
    detects_single_tags: True
    detects_bundles: False

camera_topic_prefix: "/ar_pose_marker"
