# Specify AprilTag-object relative transforms, tag sizes, and which cameras detect which tag sizes
tags:
  tag_76: # bundle master
    tag_size_cm: 7.62
    relative_frames:
      shelf: [-0.0635, -0.1651, 0.0588, 0, 0, 0] #distances in meters [x,y,z,roll,pitch,yaw]
    bundle: True

  tag_: # bundle master
    tag_size_cm: 4.0 # Length (cm) of side of tag's black square
    relative_frames:
      pb: [0.1, 0, 0, 0, 0, 0] # w.r.t. tag
    bundle: True

  tag_:
    tag_size_cm: 
    relative_frames:
      pb: [0,0,0,0,0,0]

cameras:
  left:
    recognized_tag_sizes_cm: [4.0, 7.62]
    detects_single_tags: True
    detects_bundles: True

camera_topic_prefix: "/ar_pose_marker"