# Specify AprilTag-object relative transforms, tag sizes, and which cameras detect which tag sizes
tags:
  tag_80: # Door's bundle master
    tag_size_cm: 7.62
    relative_frames:
      door_handle: [0.24, 0.1, 0.2, 0, 0, 0] #dummy
    bundle: True

  tag_60:
    tag_size_cm: 4.0 # Length (cm) of side of tag's black square
    relative_frames:
      expo_spray: [0.1, 0, 0, 0, 0, 0] # w.r.t. tag

  tag_51:
    tag_size_cm: 18.5 # Side length (cm)
    relative_frames:
      table1: [-0.1, 0, -0.5, 1.5708, 0, 0] # Roll 90 degrees so table's z-axis is "up"

  tag_50:
    tag_size_cm: 18.5 # Side length (cm)
    relative_frames:
      table2: [-0.2, 0, -0.5, 1.5708, 0, 0] # dummy
  
  tag_5:
    tag_size_cm: 4.0 # Side length (cm)
    relative_frames:
      eraser: [0, 0, -0.5, 1.5708, 0, 0] #dummy

  tag_1: # Cabinet's bundle master
    tag_size_cm: 7.62
    relative_frames:
      cabinet_handle: [0.32, 0.24, 0.18, 0, 0, 0]
    bundle: True

cameras:
  hand:
    recognized_tag_sizes_cm: [4.0]
    detects_single_tags: True
    detects_bundles: True
  frontleft:
    recognized_tag_sizes_cm: [18.5, 4.0, 7.62]
    detects_single_tags: True
    detects_bundles: True
  frontright:
    recognized_tag_sizes_cm: [18.5, 4.0, 7.62]
    detects_single_tags: True
    detects_bundles: True

camera_topic_prefix: "/ar_pose_marker"
