# End-effector trajectory while erasing, specified using body-frame 3D points.
points:
  - [1.2, 0.2, 0.5]
  - [1.2, 0.2, 0.75]
  - [1.2, 0.1, 0.75]
  - [1.2, 0.1, 0.5]
  - [1.2, 0, 0.5]
  - [1.2, 0, 0.75]
  - [1.2, -0.1, 0.75]
  - [1.2, -0.1, 0.5]
  - [1.2, -0.2, 0.75]
  - [1.2, -0.2, 0.5]
