# End-effector trajectory while erasing, specified using body-frame 3D points.
points:
  - [1.2, 0.2, 0.3]
  - [1.2, 0.2, 0.7]
  - [1.2, 0.12, 0.7]
  - [1.2, 0.12, 0.3]
  - [1.2, 0.04, 0.3]
  - [1.2, 0.04, 0.7]
  - [1.2, -0.04, 0.7]
  - [1.2, -0.04, 0.3]
  - [1.2, -0.12, 0.3]
  - [1.2, -0.12, 0.7]
  - [1.2, -0.2, 0.7]
  - [1.2, -0.2, 0.3]
