# Fiducial marker configuration for the SciLi Spot experiment
# AprilTag frame convention: x right, y down, z through

markers:
  marker_42:
    size_cm: 7.6
    relative_frames:
      black_dresser: [0.32, -0.164, 0.7, 3.14159, 0, 1.5708]

  marker_500: # Attached on top of the eraser
    size_cm: 3.6
    relative_frames: # Eraser frame is "behind" (+z) and roll 180° to flip the y- and z-axes
      eraser1: [0, 0, 0.035, 3.14159, 0, 0]

cameras: [hand] # Removed body cameras to avoid inconsistencies with the gripper
