# Fiducial marker configuration for the SciLi demos

markers:
  marker_2:
    size_cm: 4.4 # Size (cm) along one side of the marker's black square
    relative_frames: # Relative transforms (expressed w.r.t. marker frame)
      cup: [0, 0, -0.14, 0, 0, 0] # [x, y, z, roll, pitch, yaw] (angles in radians)

cameras:
  frontleft:
    recognized_sizes_cm: [4.4] # Sizes (cm) of tags that each camera is configured to recognize
  frontright:
    recognized_sizes_cm: [4.4]
  hand:
    recognized_sizes_cm: [4.4]
