(cl:in-package spot_msgs-msg)
(cl:export '(DISABLE_VISION_FOOT_OBSTACLE_AVOIDANCE-VAL
          DISABLE_VISION_FOOT_OBSTACLE_AVOIDANCE
          DISABLE_VISION_FOOT_CONSTRAINT_AVOIDANCE-VAL
          DISABLE_VISION_FOOT_CONSTRAINT_AVOIDANCE
          DISABLE_VISION_BODY_OBSTACLE_AVOIDANCE-VAL
          DISABLE_VISION_BODY_OBSTACLE_AVOIDANCE
          OBSTACLE_AVOIDANCE_PADDING-VAL
          OBSTACLE_AVOIDANCE_PADDING
          DISABLE_VISION_FOOT_OBSTACLE_BODY_ASSIST-VAL
          DISABLE_VISION_FOOT_OBSTACLE_BODY_ASSIST
          DISABLE_VISION_NEGATIVE_OBSTACLES-VAL
          DISABLE_VISION_NEGATIVE_OBSTACLES
))