(cl:in-package spot_msgs-msg)
(cl:export '(GROUND_MU_EST-VAL
          GROUND_MU_EST
          FRAME_NAME-VAL
          FRAME_NAME
          FOOT_SLIP_DISTANCE_RT_FRAME-VAL
          FOOT_SLIP_DISTANCE_RT_FRAME
          FOOT_SLIP_VELOCITY_RT_FRAME-VAL
          FOOT_SLIP_VELOCITY_RT_FRAME
          GROUND_CONTACT_NORMAL_RT_FRAME-VAL
          GROUND_CONTACT_NORMAL_RT_FRAME
          VISUAL_SURFACE_GROUND_PENETRATION_MEAN-VAL
          VISUAL_SURFACE_GROUND_PENETRATION_MEAN
          VISUAL_SURFACE_GROUND_PENETRATION_STD-VAL
          VISUAL_SURFACE_GROUND_PENETRATION_STD
))