(cl:in-package spot_msgs-msg)
(cl:export '(TAG_ID-VAL
          TAG_ID
          X-VAL
          X
          Y-VAL
          Y
          FRAME_NAME_FIDUCIAL-VAL
          FRAME_NAME_FIDUCIAL
          FIDUCIAL_POSE_STATUS-VAL
          FIDUCIAL_POSE_STATUS
          FRAME_NAME_FIDUCIAL_FILTERED-VAL
          FRAME_NAME_FIDUCIAL_FILTERED
          FIDUCIAL_FILTERED_POSE_STATUS-VAL
          FIDUCIAL_FILTERED_POSE_STATUS
          FRAME_NAME_CAMERA-VAL
          FRAME_NAME_CAMERA
          DETECTION_COVARIANCE-VAL
          DETECTION_COVARIANCE
          DETECTION_COVARIANCE_REFERENCE_FRAME-VAL
          DETECTION_COVARIANCE_REFERENCE_FRAME
))