(cl:in-package spot_msgs-msg)
(cl:export '(ACQUISITION_TIME-VAL
          ACQUISITION_TIME
          TRANSFORMS_SNAPSHOT-VAL
          TRANSFORMS_SNAPSHOT
          FRAME_NAME_IMAGE_SENSOR-VAL
          FRAME_NAME_IMAGE_SENSOR
          IMAGE-VAL
          IMAGE
          CAPTURE_EXPOSURE_DURATION-VAL
          CAPTURE_EXPOSURE_DURATION
          CAPTURE_SENSOR_GAIN-VAL
          CAPTURE_SENSOR_GAIN
))