(cl:in-package spot_msgs-msg)
(cl:export '(CAMERA_SOURCE-VAL
          CAMERA_SOURCE
          IMAGE_DATA_COORDINATES-VAL
          IMAGE_DATA_COORDINATES
          IMAGE_DATA_KEYPOINT_TYPE-VAL
          IMAGE_DATA_KEYPOINT_TYPE
          KEYPOINT_COORDINATE_X-VAL
          KEYPOINT_COORDINATE_X
          KEYPOINT_COORDINATE_Y-VAL
          KEYPOINT_COORDINATE_Y
          BINARY_DESCRIPTOR-VAL
          BINARY_DESCRIPTOR
          KEYPOINT_SCORE-VAL
          KEYPOINT_SCORE
          KEYPOINT_SIZE-VAL
          KEYPOINT_SIZE
          KEYPOINT_ANGLE-VAL
          KEYPOINT_ANGLE
          IMAGE_SOURCE-VAL
          IMAGE_SOURCE
          IMAGE_CAPTURE-VAL
          IMAGE_CAPTURE
          FRAME_NAME_IMAGE_COORDINATES-VAL
          FRAME_NAME_IMAGE_COORDINATES
))