; Auto-generated. Do not edit!


(cl:in-package spot_msgs-msg)


;//! \htmlinclude DockFeedback.msg.html

(cl:defclass <DockFeedback> (roslisp-msg-protocol:ros-message)
  ((status
    :reader status
    :initarg :status
    :type spot_msgs-msg:DockState
    :initform (cl:make-instance 'spot_msgs-msg:DockState)))
)

(cl:defclass DockFeedback (<DockFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DockFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DockFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name spot_msgs-msg:<DockFeedback> is deprecated: use spot_msgs-msg:DockFeedback instead.")))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <DockFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader spot_msgs-msg:status-val is deprecated.  Use spot_msgs-msg:status instead.")
  (status m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DockFeedback>) ostream)
  "Serializes a message object of type '<DockFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'status) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DockFeedback>) istream)
  "Deserializes a message object of type '<DockFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'status) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DockFeedback>)))
  "Returns string type for a message object of type '<DockFeedback>"
  "spot_msgs/DockFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DockFeedback)))
  "Returns string type for a message object of type 'DockFeedback"
  "spot_msgs/DockFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DockFeedback>)))
  "Returns md5sum for a message object of type '<DockFeedback>"
  "c362c4f04a7060b16832e7c8aadb5896")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DockFeedback)))
  "Returns md5sum for a message object of type 'DockFeedback"
  "c362c4f04a7060b16832e7c8aadb5896")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DockFeedback>)))
  "Returns full string definition for message of type '<DockFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%DockState status~%~%================================================================================~%MSG: spot_msgs/DockState~%# Status~%uint8 DOCK_STATUS_UNKNOWN = 0~%uint8 DOCK_STATUS_DOCKED = 1~%uint8 DOCK_STATUS_DOCKING = 2~%uint8 DOCK_STATUS_UNDOCKED = 3~%uint8 DOCK_STATUS_UNDOCKING = 4~%~%# DockType~%uint8 DOCK_TYPE_UNKNOWN = 0~%uint8 DOCK_TYPE_CONTACT_PROTOTYPE = 2~%uint8 DOCK_TYPE_SPOT_DOCK = 3~%~%# LinkStatus~%uint8 LINK_STATUS_UNKNOWN = 0~%uint8 LINK_STATUS_CONNECTED = 1~%uint8 LINK_STATUS_ERROR = 2~%uint8 LINK_STATUS_DETECTING = 3~%~%uint8 status~%uint8 dock_type~%uint32 dock_id~%uint8 power_status~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DockFeedback)))
  "Returns full string definition for message of type 'DockFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%DockState status~%~%================================================================================~%MSG: spot_msgs/DockState~%# Status~%uint8 DOCK_STATUS_UNKNOWN = 0~%uint8 DOCK_STATUS_DOCKED = 1~%uint8 DOCK_STATUS_DOCKING = 2~%uint8 DOCK_STATUS_UNDOCKED = 3~%uint8 DOCK_STATUS_UNDOCKING = 4~%~%# DockType~%uint8 DOCK_TYPE_UNKNOWN = 0~%uint8 DOCK_TYPE_CONTACT_PROTOTYPE = 2~%uint8 DOCK_TYPE_SPOT_DOCK = 3~%~%# LinkStatus~%uint8 LINK_STATUS_UNKNOWN = 0~%uint8 LINK_STATUS_CONNECTED = 1~%uint8 LINK_STATUS_ERROR = 2~%uint8 LINK_STATUS_DETECTING = 3~%~%uint8 status~%uint8 dock_type~%uint32 dock_id~%uint8 power_status~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DockFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'status))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DockFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'DockFeedback
    (cl:cons ':status (status msg))
))
