# Command the robot to release an object into the specified parent frame.
string object_name
string new_parent_frame
---
bool success
string message
geometry_msgs/PoseStamped new_pose  # It's the caller's job to update the state
