// Auto-generated. Do not edit!

// (in-package spot_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class NavigateRouteGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.waypoint_ids = null;
    }
    else {
      if (initObj.hasOwnProperty('waypoint_ids')) {
        this.waypoint_ids = initObj.waypoint_ids
      }
      else {
        this.waypoint_ids = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type NavigateRouteGoal
    // Serialize message field [waypoint_ids]
    bufferOffset = _arraySerializer.string(obj.waypoint_ids, buffer, bufferOffset, null);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type NavigateRouteGoal
    let len;
    let data = new NavigateRouteGoal(null);
    // Deserialize message field [waypoint_ids]
    data.waypoint_ids = _arrayDeserializer.string(buffer, bufferOffset, null)
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    object.waypoint_ids.forEach((val) => {
      length += 4 + _getByteLength(val);
    });
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'spot_msgs/NavigateRouteGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '118b8bcfd9aa792758857e91da4c7a89';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    string[] waypoint_ids # Waypoint id string for where to go
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new NavigateRouteGoal(null);
    if (msg.waypoint_ids !== undefined) {
      resolved.waypoint_ids = msg.waypoint_ids;
    }
    else {
      resolved.waypoint_ids = []
    }

    return resolved;
    }
};

module.exports = NavigateRouteGoal;
