# 2D Costmap parameters; Most parameters
# are defined specifically for local and global costmaps.
# ---Vector footprint (Meters):---
footprint: [[0.62, 0.25], [0.62, -0.25], [-0.6, -0.25], [-0.6, 0.25]]
