# currently we are using the most basic local planner
DWAPlannerROS:
  # Robot Configuration Parameters
  acc_lim_x: 1.5
  acc_lim_y: 1
  max_vel_theta: 0.6  # Lower from the typical 1.0
  min_vel_theta: 0.2  # Lower from the typical 0.4
  acc_lim_theta: 4.0  # Lower from the 8.0 for Spot
  
  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.17
  xy_goal_tolerance: 0.1

  # Velocity Parameters
  max_vel_x: 0.5
  min_vel_x: 0.1

  # Oscalation
  oscillation_reset_dist: 0.2
  oscillation_reset_angle: 0.2 
