# currently we are using the most basic local planner
TrajectoryPlannerROS:
  meter_scoring: true
  acc_lim_x: 1.5
  acc_lim_y: 1.5
  max_vel_x: 0.5
  min_vel_x: 0.1
  yaw_goal_tolerance: 0.0872665 # Permit 5 degrees of heading error
  xy_goal_tolerance: 0.2 # Permit 5 cm of (x,y)-position error
  sim_time: 1.0
  holonomic_robot: false
