# currently we are using the most basic local planner
# currently we are using the most basic local planner
TrajectoryPlannerROS:
  meter_scoring: true
  acc_lim_x: 1.5
  acc_lim_y: 1.5
  max_vel_x: 0.5
  min_vel_x: 0.1
  yaw_goal_tolerance: 0.7
  xy_goal_tolerance: 0.5
  sim_time: 1.0




# DWAPlannerROS:
#   # Robot Configuration Parameters
#   acc_lim_x: 1.5
#   acc_lim_y: 1.0
#   max_vel_theta: 0.5  # Lower from the typical 1.0
#   min_vel_theta: 0.1  # Lower from the typical 0.4
#   acc_lim_theta: 4.0  # Lower from the 8.0 for Spot
  
#   # Goal Tolerance Parameters
#   yaw_goal_tolerance: 2.0
#   xy_goal_tolerance: 1.0

#   # Velocity Parameters
#   max_vel_x: 0.5
#   min_vel_x: 0.1

#   # Oscalation
#   oscillation_reset_dist: 0.2
#   oscillation_reset_angle: 0.2 

#   # Trajectory Scoring Parameters
#   path_distance_bias: 40.0
#   goal_distance_bias: 20.0
#   latch_xy_goal_tolerance: false
