name: Verify Docker Images Can Be Pulled

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-docker-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Verify Docker Images Pullable
        run: bash docker/check_services_pullable.sh
