controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_sh0
      - arm_sh1
      - arm_el0
      - arm_el1
      - arm_wr0
      - arm_wr1

  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_f1x

initial:
  - group: full_robot
    pose: standing_stowed
