controller_list:
  - name: fake_spot_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_joint1
      - arm_joint2
      - arm_joint3
      - arm_joint4
      - arm_joint5
      - arm_joint6
  - name: fake_spot_body_controller
    type: $(arg fake_execution_type)
    joints:
      - front_left_hip_x
      - front_left_hip_y
      - front_left_knee
      - front_right_hip_x
      - front_right_hip_y
      - front_right_knee
      - rear_left_hip_x
      - rear_left_hip_y
      - rear_left_knee
      - rear_right_hip_x
      - rear_right_hip_y
      - rear_right_knee
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_gripper
initial:  # Define initial robot poses per group
  - group: spot_arm
    pose: arm_stowed
  - group: spot_body
    pose: default_standing