# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  arm_el0:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  arm_el1:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  arm_f1x:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  arm_sh0:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  arm_sh1:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  arm_wr0:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  arm_wr1:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  front_left_hip_x:
    has_velocity_limits: true
    max_velocity: 17.647
    has_acceleration_limits: false
    max_acceleration: 0
  front_left_hip_y:
    has_velocity_limits: true
    max_velocity: 17.647
    has_acceleration_limits: false
    max_acceleration: 0
  front_left_knee:
    has_velocity_limits: true
    max_velocity: 12
    has_acceleration_limits: false
    max_acceleration: 0
  front_right_hip_x:
    has_velocity_limits: true
    max_velocity: 17.647
    has_acceleration_limits: false
    max_acceleration: 0
  front_right_hip_y:
    has_velocity_limits: true
    max_velocity: 17.647
    has_acceleration_limits: false
    max_acceleration: 0
  front_right_knee:
    has_velocity_limits: true
    max_velocity: 12
    has_acceleration_limits: false
    max_acceleration: 0
  rear_left_hip_x:
    has_velocity_limits: true
    max_velocity: 17.647
    has_acceleration_limits: false
    max_acceleration: 0
  rear_left_hip_y:
    has_velocity_limits: true
    max_velocity: 17.647
    has_acceleration_limits: false
    max_acceleration: 0
  rear_left_knee:
    has_velocity_limits: true
    max_velocity: 12
    has_acceleration_limits: false
    max_acceleration: 0
  rear_right_hip_x:
    has_velocity_limits: true
    max_velocity: 17.647
    has_acceleration_limits: false
    max_acceleration: 0
  rear_right_hip_y:
    has_velocity_limits: true
    max_velocity: 17.647
    has_acceleration_limits: false
    max_acceleration: 0
  rear_right_knee:
    has_velocity_limits: true
    max_velocity: 12
    has_acceleration_limits: false
    max_acceleration: 0
