arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm_sh0
    - arm_sh1
    - arm_el0
    - arm_el1
    - arm_wr0
    - arm_wr1
  gains:
    arm_sh0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_sh1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_el0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_el1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_wr0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_wr1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

gripper_controller:
  type: position_controllers/GripperActionController
  joint: arm_f1x
