spot_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm_sh0
    - arm_sh1
    - arm_el0
    - arm_el1
    - arm_wr0
    - arm_wr1

gripper_controller:
  type: position_controllers/GripperActionController
  joint: arm_f1x
